package mitaller;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;

/**
 *
 * @author Andrew
 */
public class AñadirEgreso extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public AñadirEgreso() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }

    public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_izq = new javax.swing.JLabel();
        Titulo_izq = new javax.swing.JLabel();
        Titulo_central = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTN_Regresar = new javax.swing.JButton();
        titulo_txt = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        fecha_txt = new javax.swing.JLabel();
        descripcion_txt = new javax.swing.JLabel();
        provedor_txt = new javax.swing.JLabel();
        provedor = new javax.swing.JTextField();
        monto_txt = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        BTN_Agregar = new javax.swing.JButton();
        tituloabajo = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_izq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logo_izq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMiTaller2.png"))); // NOI18N
        jPanel1.add(logo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Titulo_izq.setFont(new java.awt.Font("Arial", 2, 22)); // NOI18N
        Titulo_izq.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_izq.setText("Mi Taller");
        jPanel1.add(Titulo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        Titulo_central.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        Titulo_central.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_central.setText("Añadir Egreso");
        jPanel1.add(Titulo_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_X.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -10, -1, 50));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_MINIMIZAR.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 200));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        BTN_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        titulo_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titulo_txt.setForeground(new java.awt.Color(255, 255, 255));
        titulo_txt.setText("Titulo");
        jPanel2.add(titulo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        titulo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tituloKeyTyped(evt);
            }
        });
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 210, 30));

        fecha_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        fecha_txt.setForeground(new java.awt.Color(255, 255, 255));
        fecha_txt.setText("Fecha");
        jPanel2.add(fecha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        descripcion_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        descripcion_txt.setForeground(new java.awt.Color(255, 255, 255));
        descripcion_txt.setText("Descripcion");
        jPanel2.add(descripcion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        provedor_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        provedor_txt.setForeground(new java.awt.Color(255, 255, 255));
        provedor_txt.setText("Proveedor y/o Beneficiario");
        jPanel2.add(provedor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        provedor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        provedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                provedorKeyTyped(evt);
            }
        });
        jPanel2.add(provedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 30));

        monto_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        monto_txt.setForeground(new java.awt.Color(255, 255, 255));
        monto_txt.setText("Monto");
        jPanel2.add(monto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        monto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
        });
        jPanel2.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 210, 30));

        BTN_Agregar.setBackground(new java.awt.Color(0, 102, 204));
        BTN_Agregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BTN_Agregar.setText("Agregar");
        BTN_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_AgregarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        tituloabajo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tituloabajo.setForeground(new java.awt.Color(255, 255, 255));
        tituloabajo.setText("Mi Taller");
        jPanel2.add(tituloabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, -1));

        fecha.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 210, 30));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 710, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void BTN_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RegresarMouseClicked
        this.setVisible(false);
        new MenuEgresos().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_RegresarMouseClicked

    private void BTN_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_AgregarMouseClicked
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into egresos values(?,?,?,?,?,?)");

            String TITULO = titulo.getText().trim();
            String FECHA = ((JTextField) fecha.getDateEditor().getUiComponent()).getText();
            String DESCRIPCION = descripcion.getText().trim();
            String PROVEDOR = provedor.getText().trim();
            String MONTO = monto.getText().trim();

            if (descripcion.equals("")) {
                DESCRIPCION = null;
            }

            if (provedor.equals("")) {
                PROVEDOR = null;
            }

            if (TITULO.equals("")
                    || MONTO.equals("")) {
                JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios, favor de llenarlos.", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
            } else {
                pst.setString(1, "0");
                pst.setString(2, titulo.getText().trim());
                pst.setString(3, ((JTextField) fecha.getDateEditor().getUiComponent()).getText());
                pst.setString(4, DESCRIPCION);
                pst.setString(5, PROVEDOR);
                pst.setString(6, monto.getText().trim());
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Egreso Guardado", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new AñadirEgreso().setVisible(true);
            }
        } catch (Exception e) {
            System.err.print(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_AgregarMouseClicked

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != (char) KeyEvent.VK_BACKSPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números.", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_montoKeyTyped

    private void provedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_provedorKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_provedorKeyTyped

    private void tituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_tituloKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirEgreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Agregar;
    private javax.swing.JButton BTN_Regresar;
    private javax.swing.JLabel Titulo_central;
    private javax.swing.JLabel Titulo_izq;
    private javax.swing.JLabel cerrar;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel descripcion_txt;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel fecha_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_izq;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField monto;
    private javax.swing.JLabel monto_txt;
    private javax.swing.JTextField provedor;
    private javax.swing.JLabel provedor_txt;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel titulo_txt;
    private javax.swing.JLabel tituloabajo;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
