package mitaller;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class AñadirVehiculoPresupuesto extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    Calendar hora = new GregorianCalendar();

    public void ConsultarCliente(JComboBox Clientes) {
        try {

            String[] datos = new String[2];
            String texto;
            String texto1;
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst1 = cn1.prepareStatement("select rfc,nombre from clientes");

            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                datos[0] = rs1.getString(1);
                datos[1] = rs1.getString(2);
                texto = datos[0] + " - " + datos[1];
                Clientes.addItem(texto);

            }

        } catch (SQLException e) {
            System.err.print(e);
        }
    }

    public AñadirVehiculoPresupuesto() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        ConsultarCliente(rfc_cliente);
    }

     public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    private void LimpiarTextos() {
        placas.setText(null);
        vehiculo.setText(null);
        modelo.setText(null);
        color.setText(null);
        motor.setText(null);
        kilometraje.setText(null);
        //rfc_cliente.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_izq = new javax.swing.JLabel();
        Titulo_izq = new javax.swing.JLabel();
        Titulo_central = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        BTN_Regresar = new javax.swing.JButton();
        tituloabajo = new javax.swing.JLabel();
        rfc_txt = new javax.swing.JLabel();
        placas = new javax.swing.JTextField();
        direccion_txt = new javax.swing.JLabel();
        vehiculo = new javax.swing.JTextField();
        correo_txt = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        telefono_txt = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        telefono2_txt = new javax.swing.JLabel();
        motor = new javax.swing.JTextField();
        BTN_Agregar = new javax.swing.JButton();
        telefono2_txt2 = new javax.swing.JLabel();
        kilometraje = new javax.swing.JTextField();
        telefono2_txt3 = new javax.swing.JLabel();
        rfc_cliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_izq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logo_izq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMiTaller2.png"))); // NOI18N
        jPanel1.add(logo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Titulo_izq.setFont(new java.awt.Font("Arial", 2, 22)); // NOI18N
        Titulo_izq.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_izq.setText("Mi Taller");
        jPanel1.add(Titulo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        Titulo_central.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        Titulo_central.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_central.setText("Añadir Vehiculo");
        jPanel1.add(Titulo_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_X.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 50));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_MINIMIZAR.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 710, 110));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        BTN_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        tituloabajo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tituloabajo.setForeground(new java.awt.Color(255, 255, 255));
        tituloabajo.setText("Tecno Auto");
        jPanel2.add(tituloabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 760, -1, -1));

        rfc_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        rfc_txt.setForeground(new java.awt.Color(255, 255, 255));
        rfc_txt.setText("Placas");
        jPanel2.add(rfc_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        placas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        placas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placasKeyTyped(evt);
            }
        });
        jPanel2.add(placas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, 30));

        direccion_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        direccion_txt.setForeground(new java.awt.Color(255, 255, 255));
        direccion_txt.setText("Vehiculo");
        jPanel2.add(direccion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        vehiculo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel2.add(vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 210, 30));

        correo_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        correo_txt.setForeground(new java.awt.Color(255, 255, 255));
        correo_txt.setText("Modelo");
        jPanel2.add(correo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        modelo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modeloFocusLost(evt);
            }
        });
        modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modeloKeyTyped(evt);
            }
        });
        jPanel2.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, 30));

        telefono_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        telefono_txt.setForeground(new java.awt.Color(255, 255, 255));
        telefono_txt.setText("Color");
        jPanel2.add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        color.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                colorKeyTyped(evt);
            }
        });
        jPanel2.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, 30));

        telefono2_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        telefono2_txt.setForeground(new java.awt.Color(255, 255, 255));
        telefono2_txt.setText("Motor");
        jPanel2.add(telefono2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        motor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        motor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                motorKeyTyped(evt);
            }
        });
        jPanel2.add(motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, 30));

        BTN_Agregar.setBackground(new java.awt.Color(0, 102, 204));
        BTN_Agregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BTN_Agregar.setText("Agregar");
        BTN_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_AgregarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        telefono2_txt2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        telefono2_txt2.setForeground(new java.awt.Color(255, 255, 255));
        telefono2_txt2.setText("Kilometraje");
        jPanel2.add(telefono2_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        kilometraje.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        kilometraje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kilometrajeKeyTyped(evt);
            }
        });
        jPanel2.add(kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 210, 30));

        telefono2_txt3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        telefono2_txt3.setForeground(new java.awt.Color(255, 255, 255));
        telefono2_txt3.setText("ID Cliente");
        jPanel2.add(telefono2_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jPanel2.add(rfc_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 210, 30));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 710, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void BTN_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RegresarMouseClicked
        this.setVisible(false);
        new MenuPresupuesto().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_RegresarMouseClicked

    private void placasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placasKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            c = Character.toUpperCase(c); // Convertir a mayúsculas
            evt.setKeyChar(c); // Actualizar el carácter ingresado con la versión en mayúsculas
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_placasKeyTyped

    private void modeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modeloFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloFocusLost

    private void modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloKeyTyped

    private void colorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')
                && (c != (char) KeyEvent.VK_BACKSPACE) && (c != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras.", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_colorKeyTyped

    private void motorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_motorKeyTyped

    private void BTN_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_AgregarMouseClicked
        try {

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into automovil values(?,?,?,?,?,?,?)");

            String clienteSeleccionado = (String) rfc_cliente.getSelectedItem();
            String[] datosCliente = clienteSeleccionado.split(" - ");
            String rfc = datosCliente[0];

            String PLACAS = placas.getText().trim();
            String VEH = vehiculo.getText().trim();
            String MOD = modelo.getText().trim();
            String COL = color.getText().trim();
            String MOT = motor.getText().trim();
            String KIL = kilometraje.getText().trim();
            //ConsultarCliente(rfc_cliente);

            try {
                Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
                PreparedStatement pst1 = cn.prepareStatement("select placas from automovil where placas = '" + PLACAS + "'");
                ResultSet rs1 = pst1.executeQuery();
                if (rs1.next()) {
                    JOptionPane.showMessageDialog(null, "Duplicacion en PLACAS", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
                    cn1.close();
                }
            } catch (SQLException e) {
            }

            if (VEH.equals("") || MOD.equals("")
                    || COL.equals("") || KIL.equals("")) {
                JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios, favor de llenarlos", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
            } else {
                pst.setString(1, placas.getText().trim());
                pst.setString(2, vehiculo.getText().trim());
                pst.setString(3, modelo.getText().trim());
                pst.setString(4, color.getText().trim());
                pst.setString(5, motor.getText().trim());
                pst.setString(6, kilometraje.getText().trim());
                pst.setString(7, rfc);
                pst.executeUpdate();
                LimpiarTextos();
                JOptionPane.showMessageDialog(null, "Vehiculo Guardado", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new AñadirPresupuesto1().setVisible(true);
            }
        } catch (Exception e) {
            System.err.print(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_AgregarMouseClicked

    private void kilometrajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kilometrajeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_kilometrajeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirVehiculoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirVehiculoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirVehiculoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirVehiculoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirVehiculoPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Agregar;
    private javax.swing.JButton BTN_Regresar;
    private javax.swing.JLabel Titulo_central;
    private javax.swing.JLabel Titulo_izq;
    private javax.swing.JLabel cerrar;
    private javax.swing.JTextField color;
    private javax.swing.JLabel correo_txt;
    private javax.swing.JLabel direccion_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kilometraje;
    private javax.swing.JLabel logo_izq;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField motor;
    private javax.swing.JTextField placas;
    private javax.swing.JComboBox<String> rfc_cliente;
    private javax.swing.JLabel rfc_txt;
    private javax.swing.JLabel telefono2_txt;
    private javax.swing.JLabel telefono2_txt2;
    private javax.swing.JLabel telefono2_txt3;
    private javax.swing.JLabel telefono_txt;
    private javax.swing.JLabel tituloabajo;
    private javax.swing.JTextField vehiculo;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
