package mitaller;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Andrew
 */
public class Login extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public Login() {

        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        this.Ocultar_label.setVisible(false);
    }
    
    private static boolean validarLicencia(String licenseKey) {
    try {
        URL url = new URL("http://10.0.0.8:8080/licencias/activar?claveLicencia=" + licenseKey);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("POST");

        int responseCode = connection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK) {
            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String response = reader.readLine();
            return Boolean.parseBoolean(response);
        } else {
            System.out.println("Error en la solicitud HTTP.");
            return false;
        }
    } catch (Exception e) {
        e.printStackTrace();
        return false;
    }
}


    public Connection Conectar() {
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
        } catch (SQLException e) {
            System.err.print(e.toString());
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado, comunicarse con el administrador", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        }
        return con;
    }

    @Override
     public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    private static void mostrarVentanaActivacion() {
        JFrame frame = new JFrame("Activación de licencia");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 150);

        JPanel panel = new JPanel();
        frame.add(panel);

        JLabel label = new JLabel("Introduce tu código de licencia:");
        panel.add(label);

        JTextField licenseField = new JTextField(20);
        panel.add(licenseField);

        JButton activateButton = new JButton("Activar");
        panel.add(activateButton);
        
       

        activateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String licenseKey = licenseField.getText();
                if (validarLicencia(licenseKey)) {
                    // La licencia es válida, activa la aplicación.
                    ConfiguracionInicial.marcarAplicacionComoActivada();
                    frame.dispose();
                    iniciarAplicacion();
                } else {
                    // La licencia no es válida, muestra un mensaje de error.
                    JOptionPane.showMessageDialog(null, "Error: La licencia no es válida.");
                }
            }
        });

        frame.setVisible(true);
    }

    private static void iniciarAplicacion() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        Inicio_label = new javax.swing.JLabel();
        salir_txt = new javax.swing.JButton();
        minimizar_label = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Inicio_label1 = new javax.swing.JLabel();
        usuario_label = new javax.swing.JLabel();
        usuario_txt = new javax.swing.JTextField();
        contraseña_label = new javax.swing.JLabel();
        contraseña_txt = new javax.swing.JPasswordField();
        boton_inicio_sesion = new javax.swing.JButton();
        Ver_label = new javax.swing.JLabel();
        Ocultar_label = new javax.swing.JLabel();
        creditos = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio_label.setFont(new java.awt.Font("Arial", 3, 100)); // NOI18N
        Inicio_label.setText("Mi Taller");
        getContentPane().add(Inicio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 80));

        salir_txt.setBackground(new java.awt.Color(255, 51, 51));
        salir_txt.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        salir_txt.setForeground(new java.awt.Color(255, 255, 255));
        salir_txt.setText("Salir");
        salir_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir_txtMouseClicked(evt);
            }
        });
        salir_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_txtActionPerformed(evt);
            }
        });
        getContentPane().add(salir_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 620, -1, -1));

        minimizar_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_MINIMIZAR.png"))); // NOI18N
        minimizar_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizar_labelMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, -10, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_X.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, -10, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrodeportivo (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 960, 230));

        jPanel1.setBackground(new java.awt.Color(246, 241, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio_label1.setFont(new java.awt.Font("Arial", 3, 60)); // NOI18N
        Inicio_label1.setForeground(new java.awt.Color(0, 153, 204));
        Inicio_label1.setText("Inicio sesión");
        jPanel1.add(Inicio_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 64));

        usuario_label.setFont(new java.awt.Font("Arial", 2, 40)); // NOI18N
        usuario_label.setText("Usuario");
        jPanel1.add(usuario_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 40));

        usuario_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(usuario_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 301, 42));

        contraseña_label.setFont(new java.awt.Font("Arial", 2, 40)); // NOI18N
        contraseña_label.setText("Contraseña");
        jPanel1.add(contraseña_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 40));

        contraseña_txt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(contraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 301, 46));

        boton_inicio_sesion.setBackground(new java.awt.Color(0, 102, 204));
        boton_inicio_sesion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        boton_inicio_sesion.setForeground(new java.awt.Color(255, 255, 255));
        boton_inicio_sesion.setText("Ingresar");
        boton_inicio_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_inicio_sesionMouseClicked(evt);
            }
        });
        jPanel1.add(boton_inicio_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        Ver_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        Ver_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ver_labelMouseClicked(evt);
            }
        });
        jPanel1.add(Ver_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        Ocultar_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ocultar.png"))); // NOI18N
        Ocultar_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ocultar_labelMouseClicked(evt);
            }
        });
        jPanel1.add(Ocultar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 390, 300));

        creditos.setBackground(new java.awt.Color(204, 204, 204));
        creditos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        creditos.setForeground(new java.awt.Color(153, 153, 153));
        creditos.setText("Creado por CorporationAlonsoDB");
        getContentPane().add(creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_txtActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_salir_txtActionPerformed

    private void boton_inicio_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_inicio_sesionMouseClicked
        Connection conl = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String user = usuario_txt.getText();
    String pass = contraseña_txt.getText();

    if (user.equals("") || pass.equals("")) {
        JOptionPane.showMessageDialog(this, "Uno o más campos están vacíos, favor de llenarlos", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
    } else {
        try {
            conl = Conectar();
            pst = conl.prepareStatement("select username, pass, cargo from usuarios where username=? and pass=?");
            pst.setString(1, user);
            pst.setString(2, pass);

            rs = pst.executeQuery();

            if (rs.next()) {
                String cargo = rs.getString("cargo");
                this.dispose();

                if ("administrador".equals(cargo)) {
                    new MenuPrincipal().setVisible(true);
                } else if ("empleado".equals(cargo)) {
                    new MenuPrincipalEmpleado().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Datos incorrectos, inténtelo de nuevo", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            System.err.print(e.toString());
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado, comuníquese con el administrador", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_inicio_sesionMouseClicked

    private void salir_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_txtMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "Desea salir?", "Salir", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_salir_txtMouseClicked

    private void Ver_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ver_labelMouseClicked
        Ver_label.setVisible(false);
        Ocultar_label.setVisible(true);
        contraseña_txt.setEchoChar((char) 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Ver_labelMouseClicked

    private void Ocultar_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ocultar_labelMouseClicked
        Ver_label.setVisible(true);
        Ocultar_label.setVisible(false);
        contraseña_txt.setEchoChar('●');
        // TODO add your handling code here:
    }//GEN-LAST:event_Ocultar_labelMouseClicked

    private void minimizar_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar_labelMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizar_labelMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        boolean aplicacionYaActivada = ConfiguracionInicial.aplicacionYaActivada();

        if (!aplicacionYaActivada) {
            mostrarVentanaActivacion();
        } else {
            iniciarAplicacion();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inicio_label;
    private javax.swing.JLabel Inicio_label1;
    private javax.swing.JLabel Ocultar_label;
    private javax.swing.JLabel Ver_label;
    private javax.swing.JButton boton_inicio_sesion;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel contraseña_label;
    private javax.swing.JPasswordField contraseña_txt;
    private javax.swing.JLabel creditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel minimizar_label;
    private javax.swing.JButton salir_txt;
    private javax.swing.JLabel usuario_label;
    private javax.swing.JTextField usuario_txt;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
