package mitaller;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MenuPrincipalEmpleado extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public MenuPrincipalEmpleado() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }

    String Item = "";

    @Override
     public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_izquierda = new javax.swing.JPanel();
        logotecno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TecnoNombre = new javax.swing.JLabel();
        BTN_Cerrar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        Contacto = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        btnEgresos = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        text_clientes = new javax.swing.JLabel();
        BTN_Clientes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BTN_Mecanico = new javax.swing.JButton();
        text_mecanico = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        text_vehiculo = new javax.swing.JLabel();
        BTN_Vehiculo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        text_usuarios = new javax.swing.JLabel();
        BTN_Usuarios = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        text_refacciones = new javax.swing.JLabel();
        BTN_Refaccion = new javax.swing.JButton();
        text_refacciones1 = new javax.swing.JLabel();
        texttec = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        text_usuarios2 = new javax.swing.JLabel();
        BTN_Presupuesto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BTN_Estatus = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Inventario = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BTN_BACKUP = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        label_minimizar = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_izquierda.setBackground(new java.awt.Color(0, 102, 153));
        panel_izquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logotecno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMiTaller2.png"))); // NOI18N
        panel_izquierda.add(logotecno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 46));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        panel_izquierda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TecnoNombre.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        TecnoNombre.setForeground(new java.awt.Color(255, 255, 255));
        TecnoNombre.setText("Mi Taller");
        panel_izquierda.add(TecnoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        BTN_Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        BTN_Cerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BTN_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarsesion2.png"))); // NOI18N
        BTN_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_CerrarMouseClicked(evt);
            }
        });
        panel_izquierda.add(BTN_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 50, 50));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        jButton2.setText("Acerca de");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jButton3.setText("Egresos");
        jPanel11.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Egresos");
        jPanel16.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jButton7.setText("Egresos");
        jPanel16.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jPanel11.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 80));

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setText("Egresos");
        jPanel17.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jButton9.setText("Egresos");
        jPanel17.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setText("Egresos");
        jPanel18.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jButton11.setText("Egresos");
        jPanel18.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 80));

        jPanel11.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 80));

        panel_izquierda.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 80));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contacto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Contacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contacto.png"))); // NOI18N
        Contacto.setText("Contacto");
        Contacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactoMouseClicked(evt);
            }
        });
        jPanel15.add(Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jButton5.setText("Egresos");
        jPanel15.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        panel_izquierda.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 280, 80));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEgresos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/egresos.png"))); // NOI18N
        btnEgresos.setText("Egresos");
        btnEgresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEgresosMouseClicked(evt);
            }
        });
        jPanel19.add(btnEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        jButton13.setText("Egresos");
        jPanel19.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 195, 40));

        panel_izquierda.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 80));

        getContentPane().add(panel_izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 660));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        text_clientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_clientes.setForeground(new java.awt.Color(255, 255, 255));
        text_clientes.setText("Clientes");

        BTN_Clientes.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Clientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        BTN_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_ClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(BTN_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(text_clientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(text_clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 190, 150));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        BTN_Mecanico.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Mecanico.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Mecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mecan.png"))); // NOI18N
        BTN_Mecanico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MecanicoMouseClicked(evt);
            }
        });

        text_mecanico.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_mecanico.setForeground(new java.awt.Color(255, 255, 255));
        text_mecanico.setText("Mecanicos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(text_mecanico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(BTN_Mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(text_mecanico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 190, 150));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        text_vehiculo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_vehiculo.setForeground(new java.awt.Color(255, 255, 255));
        text_vehiculo.setText("Vehiculos y entradas");

        BTN_Vehiculo.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Vehiculo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche.png"))); // NOI18N
        BTN_Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_VehiculoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BTN_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_vehiculo))
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(text_vehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 190, 150));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        text_usuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        text_usuarios.setText("Usuarios");

        BTN_Usuarios.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Usuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioo.png"))); // NOI18N
        BTN_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_UsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BTN_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text_usuarios)
                .addGap(56, 56, 56))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(text_usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 190, 150));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_refacciones.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_refacciones.setForeground(new java.awt.Color(255, 255, 255));
        text_refacciones.setText("Refacciones y");
        jPanel6.add(text_refacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        BTN_Refaccion.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Refaccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Refaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refaccionn.png"))); // NOI18N
        BTN_Refaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RefaccionMouseClicked(evt);
            }
        });
        jPanel6.add(BTN_Refaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 43, 130, 110));

        text_refacciones1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_refacciones1.setForeground(new java.awt.Color(255, 255, 255));
        text_refacciones1.setText("mano de obra");
        jPanel6.add(text_refacciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 190, 150));

        texttec.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        texttec.setForeground(new java.awt.Color(255, 255, 255));
        texttec.setText("Mi Taller");
        jPanel1.add(texttec, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        text_usuarios2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_usuarios2.setForeground(new java.awt.Color(255, 255, 255));
        text_usuarios2.setText("Presupuesto");

        BTN_Presupuesto.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Presupuesto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Presupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/presupuesto.png"))); // NOI18N
        BTN_Presupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_PresupuestoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(text_usuarios2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(BTN_Presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(text_usuarios2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_Presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 190, 150));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Historial & Estatus");

        BTN_Estatus.setBackground(new java.awt.Color(0, 102, 102));
        BTN_Estatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_Estatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/progreso.png"))); // NOI18N
        BTN_Estatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_EstatusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(BTN_Estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Estatus, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 190, 150));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresos");

        Inventario.setBackground(new java.awt.Color(0, 102, 102));
        Inventario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresos.png"))); // NOI18N
        Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 190, 150));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Backup");

        BTN_BACKUP.setBackground(new java.awt.Color(0, 102, 102));
        BTN_BACKUP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTN_BACKUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/respaldojeje.png"))); // NOI18N
        BTN_BACKUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_BACKUPMouseClicked(evt);
            }
        });
        BTN_BACKUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACKUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(BTN_BACKUP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_BACKUP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 190, 150));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

        label_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar.png"))); // NOI18N
        label_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimizarMouseClicked(evt);
            }
        });
        jPanel20.add(label_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 30));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel28.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        jPanel32.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 40));

        jPanel28.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 40, 40));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarjeje3.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel28.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 32));

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 830, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_CerrarMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CerrarMouseClicked

    private void BTN_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_ClientesMouseClicked
        this.setVisible(false);
        new MenuClientesEmpleados().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ClientesMouseClicked

    private void BTN_MecanicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MecanicoMouseClicked
         JOptionPane.showMessageDialog(this, "Solo los administradores tienen acceso", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_MecanicoMouseClicked

    private void BTN_VehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_VehiculoMouseClicked
        this.setVisible(false);
        new MenuVehiculosEmpleado().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_VehiculoMouseClicked

    private void BTN_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_UsuariosMouseClicked
        JOptionPane.showMessageDialog(this, "Solo los administradores tienen acceso", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_UsuariosMouseClicked

    private void BTN_RefaccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RefaccionMouseClicked
        this.setVisible(false);
        new MenuRefaccionesEmpleado().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_RefaccionMouseClicked

    private void BTN_PresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_PresupuestoMouseClicked
        JOptionPane.showMessageDialog(this, "Solo los administradores tienen acceso", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_PresupuestoMouseClicked

    private void BTN_EstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_EstatusMouseClicked
        this.setVisible(false);
        new MenuEstatusEmpleado().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EstatusMouseClicked

    private void InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioMouseClicked
        JOptionPane.showMessageDialog(this, "Solo los administradores tienen acceso", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_InventarioMouseClicked

    private void BTN_BACKUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_BACKUPMouseClicked
        JOptionPane.showMessageDialog(this, "Solo los administradores tienen acceso", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_BACKUPMouseClicked

    private void BTN_BACKUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACKUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_BACKUPActionPerformed

    private void label_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimizarMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_label_minimizarMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
        new MenuAcercaDeEmpleado().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void ContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactoMouseClicked
        this.setVisible(false);
        new MenuContactoEmpleado().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactoMouseClicked

    private void btnEgresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEgresosMouseClicked
       JOptionPane.showMessageDialog(this, "Solo los administradores tienen acceso", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEgresosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACKUP;
    private javax.swing.JButton BTN_Cerrar;
    private javax.swing.JButton BTN_Clientes;
    private javax.swing.JButton BTN_Estatus;
    private javax.swing.JButton BTN_Mecanico;
    private javax.swing.JButton BTN_Presupuesto;
    private javax.swing.JButton BTN_Refaccion;
    private javax.swing.JButton BTN_Usuarios;
    private javax.swing.JButton BTN_Vehiculo;
    private javax.swing.JButton Contacto;
    private javax.swing.JButton Inventario;
    private javax.swing.JLabel TecnoNombre;
    private javax.swing.JButton btnEgresos;
    private javax.swing.JLabel cerrar;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label_minimizar;
    private javax.swing.JLabel logotecno;
    private javax.swing.JPanel panel_izquierda;
    private javax.swing.JLabel text_clientes;
    private javax.swing.JLabel text_mecanico;
    private javax.swing.JLabel text_refacciones;
    private javax.swing.JLabel text_refacciones1;
    private javax.swing.JLabel text_usuarios;
    private javax.swing.JLabel text_usuarios2;
    private javax.swing.JLabel text_vehiculo;
    private javax.swing.JLabel texttec;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}

