package mitaller;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class MenuEstatus extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public MenuEstatus() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }

     public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulologo = new javax.swing.JLabel();
        tiutulo_central = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTN_AñadirEstatus = new javax.swing.JButton();
        BTN_MostrarEstatus = new javax.swing.JButton();
        BTN_EditarEstatus = new javax.swing.JButton();
        BTN_Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTN_En_Curso = new javax.swing.JButton();
        BTN_Concluidos = new javax.swing.JButton();
        BTN_EliminarEstatus = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMiTaller2.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        titulologo.setFont(new java.awt.Font("Arial", 2, 22)); // NOI18N
        titulologo.setForeground(new java.awt.Color(255, 255, 255));
        titulologo.setText("Mi Taller");
        jPanel1.add(titulologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        tiutulo_central.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        tiutulo_central.setForeground(new java.awt.Color(255, 255, 255));
        tiutulo_central.setText("Historial & Estatus ");
        jPanel1.add(tiutulo_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_X.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, -10, -1, 50));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_MINIMIZAR.png"))); // NOI18N
        minimizar.setToolTipText("");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, -10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 169));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_AñadirEstatus.setBackground(new java.awt.Color(255, 255, 255));
        BTN_AñadirEstatus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BTN_AñadirEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        BTN_AñadirEstatus.setText("Añadir Estatus");
        BTN_AñadirEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_AñadirEstatusMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_AñadirEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, -1));

        BTN_MostrarEstatus.setBackground(new java.awt.Color(255, 255, 255));
        BTN_MostrarEstatus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BTN_MostrarEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla (1).png"))); // NOI18N
        BTN_MostrarEstatus.setText("Historial");
        BTN_MostrarEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MostrarEstatusMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_MostrarEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 360, -1));

        BTN_EditarEstatus.setBackground(new java.awt.Color(255, 255, 255));
        BTN_EditarEstatus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BTN_EditarEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        BTN_EditarEstatus.setText("Editar Estatus");
        BTN_EditarEstatus.setMaximumSize(new java.awt.Dimension(285, 89));
        BTN_EditarEstatus.setMinimumSize(new java.awt.Dimension(285, 89));
        BTN_EditarEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_EditarEstatusMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_EditarEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 290, 90));

        BTN_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        BTN_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mi Taller");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, -1, -1));

        BTN_En_Curso.setBackground(new java.awt.Color(255, 255, 255));
        BTN_En_Curso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BTN_En_Curso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enProceso.png"))); // NOI18N
        BTN_En_Curso.setText("En curso");
        BTN_En_Curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_En_CursoMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_En_Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 300, -1));

        BTN_Concluidos.setBackground(new java.awt.Color(255, 255, 255));
        BTN_Concluidos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BTN_Concluidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/completado.png"))); // NOI18N
        BTN_Concluidos.setText("Concluidos");
        BTN_Concluidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_ConcluidosMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Concluidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 290, -1));

        BTN_EliminarEstatus.setBackground(new java.awt.Color(255, 255, 255));
        BTN_EliminarEstatus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BTN_EliminarEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BTN_EliminarEstatus.setText("Eliminar Estatus");
        BTN_EliminarEstatus.setMaximumSize(new java.awt.Dimension(285, 89));
        BTN_EliminarEstatus.setMinimumSize(new java.awt.Dimension(285, 89));
        BTN_EliminarEstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_EliminarEstatusMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_EliminarEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        jPanel14.setBackground(new java.awt.Color(0, 102, 153));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estatus");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 102, 153));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Historial");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 1020, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void BTN_AñadirEstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_AñadirEstatusMouseClicked
        this.setVisible(false);
        new AñadirEstatus().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_AñadirEstatusMouseClicked

    private void BTN_EditarEstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_EditarEstatusMouseClicked
        this.setVisible(false);
        new ModificarEstatus().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EditarEstatusMouseClicked

    private void BTN_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RegresarMouseClicked
        this.setVisible(false);
        new MenuPrincipal().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_RegresarMouseClicked

    private void BTN_MostrarEstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MostrarEstatusMouseClicked
        this.setVisible(false);
        new MostrarEstatus().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_MostrarEstatusMouseClicked

    private void BTN_En_CursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_En_CursoMouseClicked
        this.setVisible(false);
        new MostrarEnCurso().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_En_CursoMouseClicked

    private void BTN_ConcluidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_ConcluidosMouseClicked
        this.setVisible(false);
        new MostrarConcluidos().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ConcluidosMouseClicked

    private void BTN_EliminarEstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_EliminarEstatusMouseClicked
        this.setVisible(false);
        new EliminarEstatus().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EliminarEstatusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AñadirEstatus;
    private javax.swing.JButton BTN_Concluidos;
    private javax.swing.JButton BTN_EditarEstatus;
    private javax.swing.JButton BTN_EliminarEstatus;
    private javax.swing.JButton BTN_En_Curso;
    private javax.swing.JButton BTN_MostrarEstatus;
    private javax.swing.JButton BTN_Regresar;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel titulologo;
    private javax.swing.JLabel tiutulo_central;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
