package mitaller;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class ModificarDatosPresupuesto extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    public void ConsultarPresupuesto(JComboBox PRE) {
        try {

            String[] datos = new String[2];
            String texto;
            String texto1;
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst1 = cn1.prepareStatement("SELECT presupuesto1.id_presupuesto, clientes.nombre FROM presupuesto1, clientes WHERE presupuesto1.id_cliente = clientes.rfc ORDER BY presupuesto1.id_presupuesto DESC");

            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                datos[0] = rs1.getString(1);
                datos[1] = rs1.getString(2);
                texto = datos[0] + " - " + datos[1];
                PRE.addItem(texto);

            }

        } catch (SQLException e) {
            System.err.print(e);
        }
    }

    public void ConsultarCliente(JComboBox Clientes) {
        try {

            String[] datos = new String[2];
            String texto;
            String texto1;
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst1 = cn1.prepareStatement("select rfc,nombre from clientes");

            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                datos[0] = rs1.getString(1);
                datos[1] = rs1.getString(2);
                texto = datos[0] + " - " + datos[1];
                Clientes.addItem(texto);

            }

        } catch (SQLException e) {
            System.err.print(e);
        }
    }

    public void ConsultarAutomovil(JComboBox Clientes) {
        try {

            String[] datos = new String[2];
            String texto;
            String texto1;
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst1 = cn1.prepareStatement("select id,placas from entrada");

            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                datos[0] = rs1.getString(1);
                datos[1] = rs1.getString(2);
                texto = datos[0] + " - " + datos[1];
                Clientes.addItem(texto);

            }

        } catch (SQLException e) {
            System.err.print(e);
        }
    }

    public ModificarDatosPresupuesto() {
        this.setContentPane(fondo);
        initComponents();
        ConsultarPresupuesto(idd);
        ConsultarCliente(id_cliente2);
        ConsultarAutomovil(ID_Entrada);
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());

        fecha_presupuesto.setVisible(false);
        id_cliente2.setVisible(false);
        forma_pago.setVisible(false);
        ID_Entrada.setVisible(false);
        total.setVisible(false);
        observaciones.setVisible(false);

        fecha_txt.setVisible(false);
        id_cliente_txt.setVisible(false);
        forma_pago_txt.setVisible(false);
        id_entrada_txt.setVisible(false);
        total_txt.setVisible(false);
        observaciones_txt.setVisible(false);

        BTN.setVisible(false);
    }

     public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_izq = new javax.swing.JLabel();
        Titulo_izq = new javax.swing.JLabel();
        Titulo_central = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTN_Regresar = new javax.swing.JButton();
        observaciones_txt = new javax.swing.JLabel();
        fecha_txt = new javax.swing.JLabel();
        id_cliente_txt = new javax.swing.JLabel();
        forma_pago_txt = new javax.swing.JLabel();
        forma_pago = new javax.swing.JTextField();
        id_entrada_txt = new javax.swing.JLabel();
        total_txt = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        tituloabajo = new javax.swing.JLabel();
        fecha_presupuesto = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        id_cliente2 = new javax.swing.JComboBox<>();
        ID_Entrada = new javax.swing.JComboBox<>();
        idd = new javax.swing.JComboBox<>();
        nombre_txt1 = new javax.swing.JLabel();
        BTN_Agregar1 = new javax.swing.JButton();
        BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_izq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logo_izq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMiTaller2.png"))); // NOI18N
        jPanel1.add(logo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Titulo_izq.setFont(new java.awt.Font("Arial", 2, 22)); // NOI18N
        Titulo_izq.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_izq.setText("Mi Taller");
        jPanel1.add(Titulo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        Titulo_central.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        Titulo_central.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_central.setText("Modificar Datos Presupuesto");
        jPanel1.add(Titulo_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_X.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -10, -1, 50));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_MINIMIZAR.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        BTN_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        observaciones_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        observaciones_txt.setForeground(new java.awt.Color(255, 255, 255));
        observaciones_txt.setText("Observaciones");
        jPanel2.add(observaciones_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        fecha_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        fecha_txt.setForeground(new java.awt.Color(255, 255, 255));
        fecha_txt.setText("Fecha");
        jPanel2.add(fecha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        id_cliente_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        id_cliente_txt.setForeground(new java.awt.Color(255, 255, 255));
        id_cliente_txt.setText("ID Cliente");
        jPanel2.add(id_cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        forma_pago_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        forma_pago_txt.setForeground(new java.awt.Color(255, 255, 255));
        forma_pago_txt.setText("Forma de Pago");
        jPanel2.add(forma_pago_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        forma_pago.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        forma_pago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                forma_pagoFocusLost(evt);
            }
        });
        forma_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                forma_pagoKeyTyped(evt);
            }
        });
        jPanel2.add(forma_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 210, 30));

        id_entrada_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        id_entrada_txt.setForeground(new java.awt.Color(255, 255, 255));
        id_entrada_txt.setText("ID de entrada");
        jPanel2.add(id_entrada_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        total_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        total_txt.setForeground(new java.awt.Color(255, 255, 255));
        total_txt.setText("Total");
        jPanel2.add(total_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        total.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, 30));

        tituloabajo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tituloabajo.setForeground(new java.awt.Color(255, 255, 255));
        tituloabajo.setText("Mi Taller");
        jPanel2.add(tituloabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, -1));

        fecha_presupuesto.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(fecha_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 30));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 300, 180));

        jPanel2.add(id_cliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 210, 30));

        jPanel2.add(ID_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 210, 30));

        jPanel2.add(idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 210, 30));

        nombre_txt1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nombre_txt1.setForeground(new java.awt.Color(255, 255, 255));
        nombre_txt1.setText("ID ");
        jPanel2.add(nombre_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        BTN_Agregar1.setBackground(new java.awt.Color(0, 102, 204));
        BTN_Agregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BTN_Agregar1.setText("Buscar");
        BTN_Agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_Agregar1MouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        BTN.setBackground(new java.awt.Color(0, 102, 204));
        BTN.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BTN.setText("Actualizar");
        BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMouseClicked(evt);
            }
        });
        BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActionPerformed(evt);
            }
        });
        jPanel2.add(BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void BTN_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RegresarMouseClicked
        this.setVisible(false);
        new ModificarPresupuesto().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_RegresarMouseClicked

    private void forma_pagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_forma_pagoFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_forma_pagoFocusLost

    private void forma_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forma_pagoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')
                && (c != (char) KeyEvent.VK_BACKSPACE) && (c != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras.", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_forma_pagoKeyTyped

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != (char) KeyEvent.VK_BACKSPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números.", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyTyped

    private void BTN_Agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_Agregar1MouseClicked
        try {

            String IDSeleccionado = (String) idd.getSelectedItem();
            String[] datosPRE = IDSeleccionado.split(" - ");
            String IDD = datosPRE[0];

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from presupuesto1 where id_presupuesto = ?");
            pst.setString(1, IDD);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                fecha_presupuesto.setVisible(true);
                id_cliente2.setVisible(true);
                forma_pago.setVisible(true);
                ID_Entrada.setVisible(true);
                total.setVisible(true);
                observaciones.setVisible(true);

                fecha_txt.setVisible(true);
                id_cliente_txt.setVisible(true);
                forma_pago_txt.setVisible(true);
                id_entrada_txt.setVisible(true);
                total_txt.setVisible(true);
                observaciones_txt.setVisible(true);

                BTN_Agregar1.setVisible(false);
                BTN.setVisible(true);

                ((JTextField) fecha_presupuesto.getDateEditor().getUiComponent()).setText(rs.getString("fecha"));
                forma_pago.setText(rs.getString("forma_pago"));
                observaciones.setText(rs.getString("observaciones"));
                total.setText(rs.getString("total"));

                // Obtener cliente
                String rfcCliente = rs.getString("presupuesto1.id_cliente");
                // Buscar el nombre del cliente asociado a ese RFC
                PreparedStatement pstCliente = cn.prepareStatement("SELECT nombre FROM clientes WHERE rfc = ?");
                pstCliente.setString(1, rfcCliente);
                ResultSet rsCliente = pstCliente.executeQuery();

                if (rsCliente.next()) {
                    String nombreCliente = rsCliente.getString("nombre");
                    id_cliente2.setSelectedItem(rfcCliente + " - " + nombreCliente);
                }

                // Obtener entrada
                String entrada = rs.getString("presupuesto1.placas");
                // Buscar el nombre del cliente asociado a ese RFC
                PreparedStatement pstENT = cn.prepareStatement("SELECT placas FROM entrada WHERE id = ?");
                pstENT.setString(1, entrada);
                ResultSet rsENT = pstENT.executeQuery();

                if (rsENT.next()) {
                    String PLACASS = rsENT.getString("placas");
                    ID_Entrada.setSelectedItem(entrada + " - " + PLACASS);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Presupuesto no encontrado", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new ModificarDatosPresupuesto().setVisible(true);
            }
        } catch (Exception e) {
            System.err.print(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_Agregar1MouseClicked

    private void BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMouseClicked
        try {
            String entradaSeleccionada = (String) ID_Entrada.getSelectedItem();
            String[] datosCliente = entradaSeleccionada.split(" - ");
            String ENT = datosCliente[0];

            String IDSeleccionada = (String) idd.getSelectedItem();
            String[] datosID = IDSeleccionada.split(" - ");
            String IDD = datosID[0];

            String cliSeleccionadO = (String) id_cliente2.getSelectedItem();
            String[] datosCLI = cliSeleccionadO.split(" - ");
            String CLI = datosCLI[0];

            String Fecha = ((JTextField) fecha_presupuesto.getDateEditor().getUiComponent()).getText();
            String Observaciones = observaciones.getText().trim();
            String Forma_pago = forma_pago.getText().trim();
            String Total = total.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst = cn.prepareStatement("update presupuesto1 set id_presupuesto = ?, fecha = ?, id_cliente = ?, forma_pago = ?, observaciones = ?, placas = ?, total = ? where id_presupuesto = ?");
            pst.setString(1, IDD);
            pst.setString(2, Fecha);
            pst.setString(3, CLI);
            pst.setString(4, Forma_pago);
            pst.setString(5, Observaciones);
            pst.setString(6, ENT);
            pst.setString(7, Total);
            pst.setString(8, IDD);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Modificacion exitosa");
            this.setVisible(false);
            new ModificarDatosPresupuesto().setVisible(true);

        } catch (Exception e) {
            System.err.print(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNMouseClicked

    private void BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatosPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN;
    private javax.swing.JButton BTN_Agregar1;
    private javax.swing.JButton BTN_Regresar;
    private javax.swing.JComboBox<String> ID_Entrada;
    private javax.swing.JLabel Titulo_central;
    private javax.swing.JLabel Titulo_izq;
    private javax.swing.JLabel cerrar;
    private com.toedter.calendar.JDateChooser fecha_presupuesto;
    private javax.swing.JLabel fecha_txt;
    private javax.swing.JTextField forma_pago;
    private javax.swing.JLabel forma_pago_txt;
    private javax.swing.JComboBox<String> id_cliente2;
    private javax.swing.JLabel id_cliente_txt;
    private javax.swing.JLabel id_entrada_txt;
    private javax.swing.JComboBox<String> idd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_izq;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel nombre_txt1;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JLabel observaciones_txt;
    private javax.swing.JLabel tituloabajo;
    private javax.swing.JTextField total;
    private javax.swing.JLabel total_txt;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
