package mitaller;

import com.sun.glass.events.KeyEvent;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;

public class QuitarCosasPresupuesto extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    DefaultTableModel table = new DefaultTableModel();

    public void ConsultarCliente(JComboBox Clientes) {
        try {

            String[] datos = new String[5];
            String texto;
            Connection cn1 = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst1 = cn1.prepareStatement("SELECT presupuesto.idd, presupuesto.id_presupuesto,clientes.nombre, hoja_refacciones.nombre,presupuesto.Cantidad FROM presupuesto,hoja_refacciones,clientes,presupuesto1 WHERE hoja_refacciones.id_refaccion= presupuesto.refaccion && presupuesto1.id_presupuesto = presupuesto.id_presupuesto && presupuesto1.id_cliente = clientes.rfc ORDER BY presupuesto.idd DESC");

            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                datos[0] = rs1.getString(1);
                datos[1] = rs1.getString(2);
                datos[2] = rs1.getString(3);
                datos[3] = rs1.getString(4);
                datos[4] = rs1.getString(5);
                texto = datos[0] + "                                     " + datos[1] + "                               " + datos[2] + "          " + datos[3] + "        " + datos[4];
                Clientes.addItem(texto);

            }

        } catch (SQLException e) {
            System.err.print(e);
        }
    }

    public QuitarCosasPresupuesto() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        ConsultarCliente(ID);
        presupuesto_txt.setVisible(false);
        presupuesto.setVisible(false);
        refaccion_txt.setVisible(false);
        refaccion.setVisible(false);
        cantidad_txt.setVisible(false);
        cantidad.setVisible(false);
        BTN.setVisible(false);

    }

     public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LogoMiTaller.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo_izq = new javax.swing.JLabel();
        Titulo_izq = new javax.swing.JLabel();
        Titulo_central = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTN_Regresar = new javax.swing.JButton();
        tituloabajo = new javax.swing.JLabel();
        BTN_Agregar1 = new javax.swing.JButton();
        ID_TXT = new javax.swing.JLabel();
        refaccion_txt = new javax.swing.JLabel();
        cantidad_txt = new javax.swing.JLabel();
        refaccion = new javax.swing.JTextField();
        ID = new javax.swing.JComboBox<>();
        presupuesto = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        presupuesto_txt = new javax.swing.JLabel();
        BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_izq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logo_izq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMiTaller2.png"))); // NOI18N
        jPanel1.add(logo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Titulo_izq.setFont(new java.awt.Font("Arial", 2, 22)); // NOI18N
        Titulo_izq.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_izq.setText("Mi Taller");
        jPanel1.add(Titulo_izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        Titulo_central.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        Titulo_central.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_central.setText("Quitar Mano de obra o Refaccion");
        jPanel1.add(Titulo_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_X.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, -10, -1, 50));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTN_MINIMIZAR.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, -10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 164));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        BTN_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RegresarMouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        tituloabajo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tituloabajo.setForeground(new java.awt.Color(255, 255, 255));
        tituloabajo.setText("Mi Taller");
        jPanel2.add(tituloabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        BTN_Agregar1.setBackground(new java.awt.Color(0, 102, 204));
        BTN_Agregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BTN_Agregar1.setText("Buscar");
        BTN_Agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_Agregar1MouseClicked(evt);
            }
        });
        jPanel2.add(BTN_Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        ID_TXT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ID_TXT.setForeground(new java.awt.Color(255, 255, 255));
        ID_TXT.setText("Codigo interno - ID Presupuesto  - Nombre Cliente     - Refaccion        - Cantidad");
        jPanel2.add(ID_TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        refaccion_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        refaccion_txt.setForeground(new java.awt.Color(255, 255, 255));
        refaccion_txt.setText("ID Refaccion");
        jPanel2.add(refaccion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        cantidad_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cantidad_txt.setForeground(new java.awt.Color(255, 255, 255));
        cantidad_txt.setText("Cantidad");
        jPanel2.add(cantidad_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        refaccion.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        refaccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                refaccionKeyTyped(evt);
            }
        });
        jPanel2.add(refaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, 30));

        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 570, 30));

        presupuesto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        presupuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                presupuestoKeyTyped(evt);
            }
        });
        jPanel2.add(presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 210, 30));

        cantidad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        jPanel2.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, 30));

        presupuesto_txt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        presupuesto_txt.setForeground(new java.awt.Color(255, 255, 255));
        presupuesto_txt.setText("ID Presupuesto");
        jPanel2.add(presupuesto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        BTN.setBackground(new java.awt.Color(0, 102, 204));
        BTN.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        BTN.setText("Eliminar");
        BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMouseClicked(evt);
            }
        });
        jPanel2.add(BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 730, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Login.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void BTN_RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RegresarMouseClicked
        this.setVisible(false);
        new ModificarPresupuesto().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_RegresarMouseClicked

    private void BTN_Agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_Agregar1MouseClicked
        try {

            String IDSeleccionado = (String) ID.getSelectedItem();
            String[] datosCliente = IDSeleccionado.split(" - ");
            String ID = datosCliente[0];

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT presupuesto.idd,presupuesto.id_presupuesto, presupuesto.refaccion,presupuesto.Cantidad FROM presupuesto WHERE idd = ?");
            pst.setString(1, ID);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                BTN_Agregar1.setVisible(false);
                BTN.setVisible(true);
                presupuesto_txt.setVisible(true);
                presupuesto.setVisible(true);
                refaccion_txt.setVisible(true);
                refaccion.setVisible(true);
                cantidad_txt.setVisible(true);
                cantidad.setVisible(true);

                presupuesto.setText(rs.getString("id_presupuesto"));
                refaccion.setText(rs.getString("refaccion"));
                cantidad.setText(rs.getString("Cantidad"));

            } else {
                JOptionPane.showMessageDialog(null, "ID no encontrado", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new QuitarCosasPresupuesto().setVisible(true);
            }

        } catch (Exception e) {
            System.err.print(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_Agregar1MouseClicked

    private void refaccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refaccionKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != (char) KeyEvent.VK_BACKSPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten números.", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_refaccionKeyTyped

    private void presupuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_presupuestoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_presupuestoKeyTyped

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadKeyTyped

    private void BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMouseClicked
        try {

            String IDSeleccionada = (String) ID.getSelectedItem();
            String[] datosCliente = IDSeleccionada.split(" - ");
            String ID = datosCliente[0];

            String CANTIDAD = cantidad.getText().trim();
            double cantidadDouble = Double.parseDouble(CANTIDAD);
            String REFACCION = refaccion.getText().trim();
            String PRESUPUESTO = presupuesto.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tecnoauto", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from presupuesto where idd = ?");

            pst.setString(1, ID);
            pst.executeUpdate();
            //Valor actual
            PreparedStatement pst1 = cn.prepareStatement("SELECT total FROM presupuesto1 WHERE id_presupuesto = ?");
            pst1.setString(1, PRESUPUESTO);
            ResultSet rs1 = pst1.executeQuery();
            double totalActual = 0.0;

            if (rs1.next()) {
                totalActual = rs1.getDouble("total");
                System.out.println("Actual:" + totalActual);

                // Calcular el resultado de precio refaccion * cantidad
                PreparedStatement pst3 = cn.prepareStatement("SELECT precio FROM hoja_refacciones WHERE id_refaccion = ?");
                pst3.setString(1, REFACCION);
                ResultSet rs = pst3.executeQuery();

                if (rs.next()) {
                    double precioRefaccion = rs.getDouble("precio");
                    System.out.println("Precio de la refacción: " + precioRefaccion);

                    double resultadoMultiplicacion = (precioRefaccion * cantidadDouble) * 1.16;
                    System.out.println("Multiplicación: " + resultadoMultiplicacion);

                    // Restar el resultado al total actual
                    double nuevoTotal = totalActual - resultadoMultiplicacion;

                    // Actualizar el total en la base de datos
                    PreparedStatement pst2 = cn.prepareStatement("UPDATE presupuesto1 SET total = ? WHERE id_presupuesto = ?");
                    pst2.setDouble(1, nuevoTotal);
                    pst2.setString(2, PRESUPUESTO);
                    pst2.executeUpdate();
                } else {
                    System.out.println("No esta entrando");
                }
            }

            JOptionPane.showMessageDialog(null, "Se elimino la refaccion o mano de obra correctamente", "Mi Taller", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            new QuitarCosasPresupuesto().setVisible(true);
        } catch (Exception e) {
            System.err.print(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuitarCosasPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuitarCosasPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuitarCosasPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuitarCosasPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuitarCosasPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN;
    private javax.swing.JButton BTN_Agregar1;
    private javax.swing.JButton BTN_Regresar;
    private javax.swing.JComboBox<String> ID;
    private javax.swing.JLabel ID_TXT;
    private javax.swing.JLabel Titulo_central;
    private javax.swing.JLabel Titulo_izq;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidad_txt;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo_izq;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField presupuesto;
    private javax.swing.JLabel presupuesto_txt;
    private javax.swing.JTextField refaccion;
    private javax.swing.JLabel refaccion_txt;
    private javax.swing.JLabel tituloabajo;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_principal.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
